# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            هنگام
tagline:          'Hengam'
description: 
url:              http://hengam.community
baseurl:          /

author:
  name:           'Farzin Mohammadi'
  url:            https://twitter.com/farzin_mohammadi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hengamcommunity/hengamcommunity.github.io
