# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            هنگام
tagline:          'Hengam'
description: 
url:			http://hengamcommunity.github.io/
baseurl:     /     

author:
  name:           'Farzin Mohammadi'
  url:            https://twitter.com/farzin_mohammadi

paginate:         5

# Custom vars
version:          2.1.3

github:
  repo:           https://github.com/hengamcommunity/hengamcommunity.github.io
